# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1a289284d38536de99fcbd6d5b553ba84625fc9118680d77f5e8d2352248fec7057db0036f1991a9ad31689c739a6fcbd840fc471794e4cefca09cbd2e17e16

test:
  secret_key_base: 98839c1b35e0bea710de6e7e60da5f1a783b044a8ef7858bf50fb755eabd6f485b20237970700625563e28ca2fcfcfa0bad8fc3dda266db3df09f445114ad7a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
